
language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.0
  - 7.2

dist: xenial

addons:
  postgresql: "9.6"
  apt:
    packages:
      - chromium-chromedriver

services:
  - mysql

env:
  - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE
  - DB=pgsql MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=master

matrix:
  exclude:
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=master
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=master

before_install:
  - sudo apt-get update
  - phpenv config-rm xdebug.ini
  - cd ../..
  - git clone --mirror 'https://github.com/moodlehq/moodle-behat-extension.git' '/home/travis/.composer/cache/vcs/git-github.com-moodlehq-moodle-behat-extension.git/' || true
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3;
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv

script:
  - moodle-plugin-ci validate
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci phpdoc

  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache

# - moodle-plugin-ci phpunit    # No tests yet
  - moodle-plugin-ci behat --profile chrome